### ISSUE TITLE
Cert date error

### ISSUE THREAD

**Issue by perguth** [mehanix/arcada#7]
When trying to add doors or windows:

![image](https://user-images.githubusercontent.com/85259/204122202-d466f763-0f51-413b-982d-c987403ba27a.png)

**Comment by mehanix** [comment]
Hi, I somehow didn't see this, sorry! The Let's Encrypt certificate expired on the backend and it isn't set up for autorenewal. If you wish to play with the app in the deployed build, I can set it back up. 

Otherwise, you should clone both this repo and [arcada-backend](https://github.com/mehanix/arcada-backend) and run them both locally. 

Let me know if there is anything else I can help with! :)

**Comment by perguth** [comment]
> Otherwise, you should clone both this repo and [arcada-backend](https://github.com/mehanix/arcada-backend) and run them both locally.

Thank you for the response! That's what I did. There where a couple of things I needed to fix though, so I created a start script: https://github.com/perguth/arcada-setup

**Comment by mehanix** [comment]
That is lovely - I'll add a link to it in the readme.

Please let me know if you end up using the codebase as a base for anything - I'd love to see it 😄

**Comment by perguth** [comment]
Sure =)

**Comment by mehanix** [comment]
fixed, changed hosting providers :)
